### PR TITLE
Fix rollup builds

### LINKED ISSUE #39: Fix Rollup builds

### PR DESCRIPTION
**Pull request by nijk**
Fixes #39 and #30

### CODE REVIEW

**Comment by nijk** [comment]
@ashleyw Any thoughts on this PR?

**Comment by nijk** [comment]
@paschaldev Apologies for the amount of time it's taken me to get around to this. I've tested this with next.js and it seems to be working fine. Are you able to test this PR against #30?

**Comment by jesstelford** [comment]
I can confirm this commit is working in a next.js v7 app doing SSR 👍 

For those also blocked on this, the workaround is:

```
yarn add https://github.com/ashleyw/react-sane-contenteditable\#5ae3977b1991198c659b221ee0a6a68a240b6465
```

Which will install this fixed commit as a dependency:

```json
    "react-sane-contenteditable": "https://github.com/ashleyw/react-sane-contenteditable#5ae3977b1991198c659b221ee0a6a68a240b6465",
```

**Comment by paschaldev** [comment]
Interesting. I'll check mine

**Pull request merged**
