### PR TITLE
Enable module; commonJS

### PR DESCRIPTION
**Pull request by paschaldev**
Patch error that allow plugin to have es6 syntax after build.

### CODE REVIEW

**Comment by nijk** [comment]
@paschaldev Thanks for the PR. If you're happy to use your forked version for know I can let you know when I've solved this issues in accordance with the maintenance roadmap.

**Comment by paschaldev** [comment]
@nijk I have fixed everything. Replaced rollup with babel and used yarn instead of npm. The dev runs fine and the plugin works and fix the issue earlier reported(#32).

**Comment by nijk** [comment]
@paschaldev thanks again for your efforts, I'm wondering why we need to replace Rollup with Webpack for this use case? Whilst I'm more familiar with Webpack it seems a little overkill for our needs. I'm fairly sure we can get this working with Rollup. My plan was to have both the Dev environment and the build both running through the same bundling process so that we have the opportunity to preprocess the final build pushed to npm

**Comment by paschaldev** [comment]
@nijk No. Webpack isn't an overkill. You only used rollup to run the examples, the normal module is transpired with babel.

I'm not too familiar with rollup but from my observations yesterday, if you use rollup, you're going to have that `import` statement in the final built module which will cause more issues for browsers because they don't understand ES6 and it needs to be transpiled down again to ES5.

Although having your own build system with babel can further do that, but making your users having to do more work other than just "use the plugin" as is without doing any extra configuration on their end makes more sense.

May I know why you think webpack is an overkill?

**Comment by nijk** [comment]
Hi @paschaldev,

I aim to solve the issue of the import statement in the final build consumed by other projects, I am already working on that by moving to a peerDependencies approach. Rollup should still be a suitable solution but it needs some more investigation to assess the suitablity of supporting both a production-ready build and a dev/demo environment.

The original creator of this library (not me) must have chosen Rollup for a good reason and I think it's only right to respect that choice unless a deficiency in the current bundler can be proven.

Webpack is more appropriate for apps and Rollup is I believe the better choice for libraries as [explained here](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c). There are plenty of other React libraries (including React itself) that use Rollup. As I've said, more investigation is needed to assess whether all the current issues can be solved using Rollup. This is on the roadmap, so do please hold tight until I can put the required time into getting this right.

**Comment by paschaldev** [comment]
@nijk Well said. 

I'll watch out for updates.

**Comment by nijk** [comment]
Closing this as v1.5.0 has been released which addresses the issues.

**Pull request closed without merging**
