### PR TITLE
33 improve props pattern

### PR DESCRIPTION
**Pull request by nijk**
# What's new/changed?

1. Remove `componentWillUpdate` pattern and replace with `componentDidUpdate`
2. Refactor to allow `props.content` to re-render the component
3. Moved utils to separate file
4. Refactor caret position calculations
5. Refactor `onKeyDown` & `onKeyUp` handlers
6. Reactor handling of `sanitise` to remove `trims leading & trailing whitespace`, this can now be handled by providing `props.sanitise` as a function if this behaviour is required. This function will receive `value` and `range` as args, allowing the implementing code to decide how the value should be sanitised with additional information from the range.
7. Refactor of the unit tests, many were employing workarounds due to the previous approach taken within the component

### CODE REVIEW

**Comment by sahildev-jd** [comment]
@nijk I was facing the content prop update issue and I tried this PR with my project. The issue that I faced is that it is setting the caret position even when I pass focus prop as false. And I added my own keyboard navigation logic. So if there is any way we can disable it from props, it would be great. Thanks :) 

Watching this PR now.

**Comment by nijk** [comment]
@sahildev-jd I'm afraid I don't fully understand what you require here. Perhaps you could provide a minimal reproduction of the issue in https://codesandbox.io?

**Comment by nijk** [comment]
@sahildev-jd I've taken a look at the code and think I see the issue now. I'll update this PR shortly

**Comment by nijk** [comment]
@sahildev-jd Can you pull the latest version of this branch and test again please?

**Comment by sahildev-jd** [comment]
@nijk Thanks for getting back so quickly. I tried with the latest version. 
The focus issue is now solved but the original issue of `content not getting updated with changing props` is not solved now. The content was updating earlier when the content prop changed. But it's not working now.

**Comment by nijk** [comment]
That's interesting, the unit tests are all passing so I think I'm going to
need a code sandbox to progress this any further.

**Comment by nijk** [comment]
@sahildev-jd I haven't been able to replicate your reported issue with content not updating via props. I've created a [Code Sandbox here](https://deem1.codesandbox.io/) that can be manipulated via the React dev tools to change the props. Please do clone the sandbox and adjust accordingly to demonstrate the problem.

**Comment by ashleyw** [comment]
Resolves https://github.com/ashleyw/react-sane-contenteditable/pull/57
Resolves https://github.com/ashleyw/react-sane-contenteditable/issues/56

**Pull request merged**
